name: Update version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.get_version.outputs.MajorMinorPatch }}
      major: ${{ steps.get_version.outputs.Major }}
      minor: ${{ steps.get_version.outputs.Minor }}
      patch: ${{ steps.get_version.outputs.Patch}}
    steps:
        - uses: actions/checkout@v4
          name: Checkout
          with:
            fetch-depth: 0
        - uses: gittools/actions/gitversion/setup@v0
          name: Install Giversion 5.x
          with:
            versionSpec: '5.x'
        - uses: gittools/actions/gitversion/execute@v0
          id: get_version
          name: Determine Version
          with:
            useConfigFile: true
            configFilePath: '.gitversion'
  tagging:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: version
    permissions:
      contents: write
    env:
      semVer: ${{ needs.version.outputs.semVer }}
      major: ${{ needs.version.outputs.major }}
      minor: ${{ needs.version.outputs.minor }}
      patch: ${{ needs.version.outputs.patch }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
        DRY_RUN: true
        MAJOR_STRING_TOKEN: ${{ env.major }}
        MINOR_STRING_TOKEN: ${{ env.minor }}
        PATCH_STRING_TOKEN: ${{ env.patch }}
