# This workflow will build a golang project

name: Go-CLI-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  version:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
          name: Checkout
          with:
            fetch-depth: 0
        - uses: gittools/actions/gitversion/setup@v0
          name: Install Giversion 5.x
          with:
            versionSpec: '5.x'
        - uses: gittools/actions/gitversion/execute@v0
          id: get_version
          name: Determine Version
          with:
            useConfigFile: true
            configFilePath: '.gitversion'
        

  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Install dependencies
      run: go get .
        
    - name: Build
      run: go build -o task-cli

    #- name: Test
    #  run: go test -v ./...
